export * from './axios.config'
export * from './build.config'
export * from './dayjs.config'
export * from './head.config'
export * from './i18n.config'
export * from './module.config'
export * from './toast.config'
export * from './vuetify.config'
